/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Verify credentials and start a session (401 with a uniform message).
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke the caller's session and its current refresh token (204).
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout-cookie": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout Cookie
         * @description Clear the refresh cookie and revoke the session it points at (204).
         *
         *     Idempotent: a missing/unknown cookie still clears the cookie and answers
         *     204. Revocation mirrors ``POST /auth/logout`` (session record + current
         *     refresh token die together).
         */
        post: operations["logout_cookie_api_v1_auth_logout_cookie_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return the authenticated user's public profile.
         */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Rotate a refresh token; reuse of an old token revokes the session.
         */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh-cookie": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Cookie
         * @description Rotate the refresh token carried in the ``kh_refresh`` httpOnly cookie.
         *
         *     With a cookie present: identical semantics to ``POST /auth/refresh``
         *     (same KV keys, same reuse detection); the rotated token is returned in
         *     the body AND set as the new cookie (HttpOnly, Secure, SameSite=Lax,
         *     path=/api/v1/auth).
         *
         *     Session probe (T14.1): a request carrying NO ``kh_refresh`` cookie at
         *     all answers 200 ``{"session": false}`` and sets no cookie — the web
         *     boot probes this endpoint whenever no cookie exists, and that expected
         *     empty state must not pollute devtools with 401s. A cookie that IS
         *     present but invalid/expired/revoked/reused still 401s exactly like the
         *     JSON transport.
         */
        post: operations["refresh_cookie_api_v1_auth_refresh_cookie_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Create a profile and start a session (201 with a fresh token pair).
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description List the caller's LIVE sessions, newest TTLs included (200).
         *
         *     The per-user index is pruned of dead members on read, so the response
         *     only ever shows sessions that can actually still refresh. ``current`` is
         *     the ``sid`` claim of the caller's own access token (ADR-0002); ``null``
         *     when the token carries no ``sid`` claim (current session unknown).
         */
        get: operations["list_sessions_api_v1_auth_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions/revoke-others": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke Other Sessions
         * @description Revoke every live session of the caller EXCEPT the current one.
         *
         *     Same teardown semantics as ``POST /auth/logout`` per victim session:
         *     ``sess:<sid>`` + its current ``rt:<hash>`` die together, and the sid is
         *     removed from the profile's index. Idempotent — with nothing else live it
         *     answers ``{"revoked": 0}``. 409 when the caller's token has no ``sid``
         *     claim (nothing is revoked: refusing beats guessing what to keep).
         */
        post: operations["revoke_other_sessions_api_v1_auth_sessions_revoke_others_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/budgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Budgets
         * @description Budget vs spend for one month (``?ym=YYYY-MM``, default: current).
         */
        get: operations["get_budgets_api_v1_budgets_get"];
        /**
         * Put Budgets
         * @description Upsert the caller's budget; returns the GET view for the current month.
         */
        put: operations["put_budgets_api_v1_budgets_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/debts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Debts
         * @description List the caller's debts, newest first, keyset-paginated.
         *
         *     ``?status=open`` (default) keeps rows with ``settled_at IS NULL``;
         *     ``settled`` the complement; ``all`` both.
         */
        get: operations["list_debts_api_v1_debts_get"];
        put?: never;
        /**
         * Create Debt
         * @description Record one debt (201 with the stored row; ``iso`` defaults to today).
         */
        post: operations["create_debt_api_v1_debts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/debts/{debt_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Debt
         * @description Delete the caller's debt (204; unknown/foreign id → 404).
         */
        delete: operations["delete_debt_api_v1_debts__debt_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Debt
         * @description Partially update the caller's debt (omitted fields stay as-is).
         */
        patch: operations["update_debt_api_v1_debts__debt_id__patch"];
        trace?: never;
    };
    "/api/v1/debts/{debt_id}/pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pay Debt
         * @description Close out a debt with a payment.
         *
         *     ``amt >= debt.amt`` → FULL: the debt settles (``settled_at`` = now UTC,
         *     the stored amount is left untouched — overpay is not recorded).
         *     ``0 < amt < debt.amt`` → PARTIAL: the remaining amount shrinks.
         *     Paying an already-settled debt → 409 ``debt_already_settled``.
         */
        post: operations["pay_debt_api_v1_debts__debt_id__pay_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Expenses
         * @description List the caller's expenses, newest first, keyset-paginated.
         */
        get: operations["list_expenses_api_v1_expenses_get"];
        put?: never;
        /**
         * Create Expense
         * @description Record one expense (201 with the stored row).
         */
        post: operations["create_expense_api_v1_expenses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/expenses/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Expenses Bulk
         * @description Insert up to 50 expenses for the caller in a single flush.
         */
        post: operations["create_expenses_bulk_api_v1_expenses_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/expenses/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Khata Categories
         * @description Distinct khatas derived from the caller's expense history (ADR-0019).
         *
         *     One row per distinct ``cat``: ``grp``/``last_used`` come from the khata's
         *     most recent expense (window pass, portable across SQLite/Postgres — no
         *     ``DISTINCT ON``), ``use_count`` from a partition count. Ordered
         *     most-used → most-recent → cat. A khata set is bounded by the user's own
         *     distinct cats, so it is picker-sized and unpaginated.
         */
        get: operations["list_khata_categories_api_v1_expenses_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/expenses/{expense_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Expense
         * @description Delete the caller's expense (204; unknown/foreign id → 404).
         */
        delete: operations["delete_expense_api_v1_expenses__expense_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Expense
         * @description Partially update the caller's expense (omitted fields stay as-is).
         */
        patch: operations["update_expense_api_v1_expenses__expense_id__patch"];
        trace?: never;
    };
    "/api/v1/export/backup.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Backup Json
         * @description Dump the caller's complete ledger as one JSON envelope (ADR-0012).
         *
         *     Every column of every expenses/debts/budgets row; rows are ordered
         *     deterministically (``iso ASC, id ASC`` — the CSV export's order) so the
         *     same data always yields the same document modulo ``exported_at``.
         */
        get: operations["export_backup_json_api_v1_export_backup_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export/expenses.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Expenses Csv
         * @description Stream the caller's expenses as a Bengali-friendly CSV attachment.
         */
        get: operations["export_expenses_csv_api_v1_export_expenses_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export/sheets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Sheets */
        post: operations["export_sheets_api_v1_export_sheets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export/sheets/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sheets Status */
        get: operations["sheets_status_api_v1_export_sheets_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_api_v1_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/import/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Restore
         * @description REPLACE the caller's ledger with the uploaded backup (v1/v2, ADR-0012).
         *
         *     The whole swap is one transaction: delete the caller's budgets, debts,
         *     expenses AND recurring rules, insert the uploaded rows with fresh PKs,
         *     commit. Recurring rows are wiped for BOTH versions — a v1 file predates
         *     rules, so restoring it means the ledger equals the file (ADR-0028).
         *     Rows whose validation fails never reach the database; a failure
         *     mid-insert rolls the deletes back too.
         */
        post: operations["import_restore_api_v1_import_restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recurring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Recurring
         * @description List the caller's rules, newest first, keyset-paginated.
         *
         *     ``?active=true`` keeps only running rules, ``false`` only paused ones;
         *     omit for both.
         */
        get: operations["list_recurring_api_v1_recurring_get"];
        put?: never;
        /**
         * Create Recurring
         * @description Create one rule (201 with the stored row).
         *
         *     ``start_date`` is the FIRST occurrence and defaults to today; the
         *     materialization cursor starts there: ``next_run = start_date``.
         */
        post: operations["create_recurring_api_v1_recurring_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recurring/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Recurring
         * @description Materialize every due occurrence of the caller's active rules (ADR-0014).
         *
         *     A rule is due while ``next_run <= today``. Each due occurrence becomes one
         *     ``expenses`` row with ``iso`` = the occurrence date (catch-up included, up
         *     to :data:`_MAX_CATCH_UP` per rule); then ``next_run`` moves past ``today``.
         *     Paused (``active=false``) and future-dated rules are skipped. Re-running
         *     the same day is a no-op: ``created: 0`` — the idempotency contract.
         */
        post: operations["run_recurring_api_v1_recurring_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recurring/{recurring_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Recurring
         * @description Delete the caller's rule (204; unknown/foreign id → 404).
         *
         *     Deleting a rule never touches expenses it already materialized.
         */
        delete: operations["delete_recurring_api_v1_recurring__recurring_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Recurring
         * @description Partially update the caller's rule (omitted fields stay as-is).
         *
         *     ``next_run`` is server-owned and forward-only (ADR-0014 §3): if the patch
         *     changes ``freq`` or ``start_date``, the cursor is clamped to
         *     ``max(current next_run, new start_date)`` — it can advance (a later
         *     start_date postpones materialization) but never rewind (which would
         *     re-materialize occurrences that already became expenses).
         */
        patch: operations["update_recurring_api_v1_recurring__recurring_id__patch"];
        trace?: never;
    };
    "/api/v1/reports/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Monthly Report
         * @description Aggregates for one month (``?ym=YYYY-MM``, default: current month).
         */
        get: operations["monthly_report_api_v1_reports_monthly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/yearly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Yearly Report
         * @description Aggregates for one year (``?year=YYYY``, default: current year).
         */
        get: operations["yearly_report_api_v1_reports_yearly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/voice/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse Transcript
         * @description Rule-parse a Bengali voice transcript into expense candidates.
         *
         *     The keyword matcher is extended with the caller's history-derived khatas
         *     (ADR-0019) — every khata the user has ever saved is recognised on the
         *     next transcript, free of any AI/token cost. Pure SQL + rules.
         */
        post: operations["parse_transcript_api_v1_voice_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return platform-wide summary statistics. */
        get: operations["get_platform_stats_api_v1_admin_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search and list all users with aggregated financial metrics. */
        get: operations["list_admin_users_api_v1_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch complete user profile and aggregated metrics. */
        get: operations["get_admin_user_detail_api_v1_admin_users__user_id__get"];
        put?: never;
        post?: never;
        /** Permanently delete a user */
        delete: operations["delete_admin_user"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return expenses for a specific user. */
        get: operations["get_admin_user_expenses_api_v1_admin_users__user_id__expenses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/debts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return all debts for a specific user. */
        get: operations["get_admin_user_debts_api_v1_admin_users__user_id__debts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/recurring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return recurring expense rules for a specific user. */
        get: operations["get_admin_user_recurring_api_v1_admin_users__user_id__recurring_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Suspend or reactivate a user */
        post: operations["suspend_admin_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuthOut
         * @description Login/register/refresh response: user + token pair.
         */
        AuthOut: {
            /** Accesstoken */
            accessToken: string;
            /** Refreshtoken */
            refreshToken: string;
            user: components["schemas"]["UserOut"];
        };
        /**
         * BackupBudgetRow
         * @description One budgets row (at most one per user — the PK is ``user_id``).
         */
        BackupBudgetRow: {
            /** Cats */
            cats: {
                [key: string]: string;
            };
            /** Total */
            total: string;
            /** Updated At */
            updated_at: string;
            /** User Id */
            user_id: string;
        };
        /**
         * BackupCounts
         * @description Row counts, mirroring the collections of the same envelope.
         */
        BackupCounts: {
            /** Budgets */
            budgets: number;
            /** Debts */
            debts: number;
            /** Expenses */
            expenses: number;
            /**
             * Recurring
             * @default 0
             */
            recurring: number;
        };
        /**
         * BackupEnvelope
         * @description The full-fidelity backup document (both directions, ADR-0012/0028).
         *
         *     ``expenses``/``debts`` reuse :class:`ExpenseOut`/:class:`DebtOut`, so the
         *     backup wire shape IS the CRUD wire shape (every column, money as exact
         *     decimal strings) — a downloaded file can be fed straight back to
         *     ``POST /import/restore``. ``recurring`` (v2, ADR-0028) carries the
         *     caller's rules; it defaults to empty so v1 consumers ignore it safely.
         */
        BackupEnvelope: {
            /** Budgets */
            budgets: components["schemas"]["BackupBudgetRow"][];
            counts: components["schemas"]["BackupCounts"];
            /** Debts */
            debts: components["schemas"]["DebtOut"][];
            /** Expenses */
            expenses: components["schemas"]["ExpenseOut"][];
            /** Exported At */
            exported_at: string;
            /** Recurring */
            recurring?: components["schemas"]["BackupRecurringRow"][];
            /**
             * Schema Version
             * @default 2
             * @constant
             */
            schema_version: 2;
        };
        /**
         * BackupRecurringRow
         * @description One recurring-rule row (ADR-0028) — every column EXCEPT ``id``/``user_id``.
         *
         *     Rules have no history to preserve beyond their content, so unlike
         *     expenses/debts the export omits identity entirely: restore always mints
         *     fresh PKs under the caller. Field validators/amount types are the shared
         *     :mod:`app.schemas.recurring` ones (do not drift — ADR-0004).
         */
        BackupRecurringRow: {
            /** Active */
            active: boolean;
            /** Amt */
            amt: string;
            /** Cat */
            cat: string;
            /** Created At */
            created_at?: string | null;
            /** Desc */
            desc?: string | null;
            /**
             * Freq
             * @enum {string}
             */
            freq: "daily" | "weekly" | "monthly" | "yearly";
            /**
             * Grp
             * @enum {string}
             */
            grp: "food" | "housing" | "utility" | "transport" | "health" | "education" | "personal" | "other";
            /**
             * Next Run
             * Format: date
             */
            next_run: string;
            /**
             * Pay
             * @enum {string}
             */
            pay: "cash" | "bkash" | "nagad" | "rocket" | "card" | "bank";
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * BudgetCatUsage
         * @description Per-category budget vs actual spend for one month.
         */
        BudgetCatUsage: {
            /** Budget */
            budget: string;
            /** Spent */
            spent: string;
            /** Usage Pct */
            usage_pct: number;
        };
        /**
         * BudgetIn
         * @description PUT /budgets body — both fields optional (partial upsert).
         */
        BudgetIn: {
            /** Cats */
            cats?: {
                [key: string]: string;
            } | null;
            /** Total */
            total?: string | null;
        };
        /**
         * BudgetOut
         * @description GET /budgets body: stored budget merged with that month's spending.
         */
        BudgetOut: {
            /** By Cat */
            by_cat: {
                [key: string]: components["schemas"]["BudgetCatUsage"];
            };
            /** Cats */
            cats: {
                [key: string]: string;
            };
            /** Spent */
            spent: string;
            /** Total */
            total: string;
            /** Usage Pct */
            usage_pct: number;
            /** Ym */
            ym: string;
        };
        /**
         * BulkExpensesIn
         * @description POST /expenses/bulk body (voice multi-item inserts).
         */
        BulkExpensesIn: {
            /** Items */
            items: components["schemas"]["ExpenseIn"][];
        };
        /** BulkExpensesOut */
        BulkExpensesOut: {
            /** Items */
            items: components["schemas"]["ExpenseOut"][];
        };
        /**
         * DebtIn
         * @description POST /debts body. ``iso`` defaults to today (router fills it).
         */
        DebtIn: {
            /**
             * Amt
             * @example 890.00
             */
            amt: string;
            /**
             * Dir
             * @enum {string}
             */
            dir: "lend" | "borrow";
            /** Iso */
            iso?: string | null;
            /** Note */
            note?: string | null;
            /** Party */
            party: string;
        };
        /**
         * DebtListOut
         * @description Envelope for GET /debts (ADR-0004 §8).
         */
        DebtListOut: {
            /** Items */
            items: components["schemas"]["DebtOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * DebtOut
         * @description Public debt row; keys mirror the DB columns exactly.
         */
        DebtOut: {
            /** Amt */
            amt: string;
            /** Created At */
            created_at: string;
            /**
             * Dir
             * @enum {string}
             */
            dir: "lend" | "borrow";
            /** Id */
            id: string;
            /**
             * Iso
             * Format: date
             */
            iso: string;
            /** Note */
            note?: string | null;
            /** Party */
            party: string;
            /** Settled At */
            settled_at?: string | null;
            /** User Id */
            user_id: string;
        };
        /**
         * DebtPayIn
         * @description POST /debts/{id}/pay body — the amount being paid back.
         */
        DebtPayIn: {
            /**
             * Amt
             * @example 890.00
             */
            amt: string;
        };
        /**
         * DebtPayOut
         * @description Pay close-out result: FULL settles the debt, PARTIAL reduces it.
         */
        DebtPayOut: {
            debt: components["schemas"]["DebtOut"];
            /**
             * Status
             * @enum {string}
             */
            status: "FULL" | "PARTIAL";
        };
        /**
         * DebtUpdate
         * @description PATCH /debts/{id} body — every field optional (partial update).
         */
        DebtUpdate: {
            /** Amt */
            amt?: string | null;
            /** Dir */
            dir?: ("lend" | "borrow") | null;
            /** Iso */
            iso?: string | null;
            /** Note */
            note?: string | null;
            /** Party */
            party?: string | null;
        };
        /**
         * ExpenseIn
         * @description POST /expenses and POST /expenses/bulk item body.
         */
        ExpenseIn: {
            /**
             * Amt
             * @example 890.00
             */
            amt: string;
            /** Cat */
            cat: string;
            /** Desc */
            desc?: string | null;
            /**
             * Grp
             * @enum {string}
             */
            grp: "food" | "housing" | "utility" | "transport" | "health" | "education" | "personal" | "other";
            /**
             * Iso
             * Format: date
             */
            iso: string;
            /**
             * Pay
             * @default cash
             * @enum {string}
             */
            pay: "cash" | "bkash" | "nagad" | "rocket" | "card" | "bank";
        };
        /**
         * ExpenseListOut
         * @description Envelope for every list endpoint (ADR-0004 §8).
         */
        ExpenseListOut: {
            /** Items */
            items: components["schemas"]["ExpenseOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * ExpenseOut
         * @description Public expense row; keys mirror the DB columns exactly.
         */
        ExpenseOut: {
            /** Amt */
            amt: string;
            /** Cat */
            cat: string;
            /** Created At */
            created_at: string;
            /** Desc */
            desc?: string | null;
            /**
             * Grp
             * @enum {string}
             */
            grp: "food" | "housing" | "utility" | "transport" | "health" | "education" | "personal" | "other";
            /** Id */
            id: string;
            /**
             * Iso
             * Format: date
             */
            iso: string;
            /**
             * Pay
             * @enum {string}
             */
            pay: "cash" | "bkash" | "nagad" | "rocket" | "card" | "bank";
            /** User Id */
            user_id: string;
        };
        /**
         * ExpenseUpdate
         * @description PATCH /expenses/{id} body — every field optional (partial update).
         */
        ExpenseUpdate: {
            /** Amt */
            amt?: string | null;
            /** Cat */
            cat?: string | null;
            /** Desc */
            desc?: string | null;
            /** Grp */
            grp?: ("food" | "housing" | "utility" | "transport" | "health" | "education" | "personal" | "other") | null;
            /** Iso */
            iso?: string | null;
            /** Pay */
            pay?: ("cash" | "bkash" | "nagad" | "rocket" | "card" | "bank") | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Healthz */
        Healthz: {
            /** Env */
            env: string;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * KhataListOut
         * @description Envelope for GET /expenses/categories (ADR-0004 §8; cursor always null).
         */
        KhataListOut: {
            /** Items */
            items: components["schemas"]["KhataOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * KhataOut
         * @description One distinct khata (category) derived from the caller's history.
         *
         *     ``grp``/``last_used`` come from the khata's *most recent* expense and are
         *     prefill hints only — reports/budgets keep grouping each expense row by its
         *     own ``grp`` (ADR-0019).
         */
        KhataOut: {
            /** Cat */
            cat: string;
            /**
             * Grp
             * @enum {string}
             */
            grp: "food" | "housing" | "utility" | "transport" | "health" | "education" | "personal" | "other";
            /**
             * Last Used
             * Format: date
             */
            last_used: string;
            /** Use Count */
            use_count: number;
        };
        /**
         * LoginIn
         * @description POST /auth/login body.
         */
        LoginIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MonthlyReportOut */
        MonthlyReportOut: {
            /** By Day */
            by_day: components["schemas"]["ReportByDay"][];
            /** By Group */
            by_group: {
                [key: string]: string;
            };
            /** Count */
            count: number;
            /** Total */
            total: string;
            /** Ym */
            ym: string;
        };
        /**
         * ParsedItem
         * @description One expense candidate extracted from a transcript segment.
         */
        ParsedItem: {
            /** Amt */
            amt: string;
            /** Cat */
            cat: string;
            /** Desc */
            desc?: string | null;
            /**
             * Grp
             * @enum {string}
             */
            grp: "food" | "housing" | "utility" | "transport" | "health" | "education" | "personal" | "other";
            /** Iso */
            iso?: string | null;
            /** Pay */
            pay?: ("cash" | "bkash" | "nagad" | "rocket" | "card" | "bank") | null;
        };
        /**
         * RecurringIn
         * @description POST /recurring body. ``start_date`` defaults to today (router fills).
         */
        RecurringIn: {
            /**
             * Amt
             * @example 890.00
             */
            amt: string;
            /** Cat */
            cat: string;
            /** Desc */
            desc?: string | null;
            /**
             * Freq
             * @enum {string}
             */
            freq: "daily" | "weekly" | "monthly" | "yearly";
            /**
             * Grp
             * @enum {string}
             */
            grp: "food" | "housing" | "utility" | "transport" | "health" | "education" | "personal" | "other";
            /**
             * Pay
             * @default cash
             * @enum {string}
             */
            pay: "cash" | "bkash" | "nagad" | "rocket" | "card" | "bank";
            /** Start Date */
            start_date?: string | null;
        };
        /**
         * RecurringListOut
         * @description Envelope for GET /recurring (ADR-0004 §8).
         */
        RecurringListOut: {
            /** Items */
            items: components["schemas"]["RecurringOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * RecurringOut
         * @description Public rule row; keys mirror the DB columns exactly.
         */
        RecurringOut: {
            /** Active */
            active: boolean;
            /** Amt */
            amt: string;
            /** Cat */
            cat: string;
            /** Created At */
            created_at: string;
            /** Desc */
            desc?: string | null;
            /**
             * Freq
             * @enum {string}
             */
            freq: "daily" | "weekly" | "monthly" | "yearly";
            /**
             * Grp
             * @enum {string}
             */
            grp: "food" | "housing" | "utility" | "transport" | "health" | "education" | "personal" | "other";
            /** Id */
            id: string;
            /**
             * Next Run
             * Format: date
             */
            next_run: string;
            /**
             * Pay
             * @enum {string}
             */
            pay: "cash" | "bkash" | "nagad" | "rocket" | "card" | "bank";
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** Updated At */
            updated_at: string;
            /** User Id */
            user_id: string;
        };
        /**
         * RecurringRunOut
         * @description POST /recurring/run result: what THIS run materialized (ADR-0014 §4).
         *
         *     ``created == len(expenses)``; ``rules`` is how many due rules were
         *     processed. A repeat run the same day returns ``created: 0`` — the
         *     idempotency guarantee.
         */
        RecurringRunOut: {
            /** Created */
            created: number;
            /** Expenses */
            expenses: components["schemas"]["ExpenseOut"][];
            /**
             * Ran On
             * Format: date
             */
            ran_on: string;
            /** Rules */
            rules: number;
        };
        /**
         * RecurringUpdate
         * @description PATCH /recurring/{id} body — every field optional (partial update).
         */
        RecurringUpdate: {
            /** Active */
            active?: boolean | null;
            /** Amt */
            amt?: string | null;
            /** Cat */
            cat?: string | null;
            /** Desc */
            desc?: string | null;
            /** Freq */
            freq?: ("daily" | "weekly" | "monthly" | "yearly") | null;
            /** Grp */
            grp?: ("food" | "housing" | "utility" | "transport" | "health" | "education" | "personal" | "other") | null;
            /** Pay */
            pay?: ("cash" | "bkash" | "nagad" | "rocket" | "card" | "bank") | null;
            /** Start Date */
            start_date?: string | null;
        };
        /**
         * RefreshIn
         * @description POST /auth/refresh body.
         */
        RefreshIn: {
            /** Refreshtoken */
            refreshToken: string;
        };
        /**
         * RegisterIn
         * @description POST /auth/register body.
         */
        RegisterIn: {
            /** Email */
            email: string;
            /** Name */
            name?: string | null;
            /** Password */
            password: string;
        };
        /** ReportByDay */
        ReportByDay: {
            /**
             * Iso
             * Format: date
             */
            iso: string;
            /** Total */
            total: string;
        };
        /** ReportByMonth */
        ReportByMonth: {
            /** Total */
            total: string;
            /** Ym */
            ym: string;
        };
        /**
         * RestoreOut
         * @description POST /import/restore response.
         */
        RestoreOut: {
            restored: components["schemas"]["BackupCounts"];
        };
        /**
         * RevokeOthersOut
         * @description POST /auth/sessions/revoke-others response.
         */
        RevokeOthersOut: {
            /** Revoked */
            revoked: number;
        };
        /**
         * SessionItemOut
         * @description One live session of the caller (GET /auth/sessions item).
         *
         *     ``expires_in`` is the remaining KV TTL of ``sess:<id>`` in seconds —
         *     the same lifetime the refresh token has left.
         */
        SessionItemOut: {
            /** Expires In */
            expires_in: number;
            /** Id */
            id: string;
        };
        /**
         * SessionProbeOut
         * @description ``POST /auth/refresh-cookie`` answer when the request carries NO
         *     ``kh_refresh`` cookie at all: there is no cookie session, so the endpoint
         *     answers 200 ``{"session": false}`` instead of 401 (keeps browser
         *     devtools/consoles free of *expected* 401 noise). A cookie that IS present
         *     but invalid/expired/revoked still 401s like the JSON transport.
         */
        SessionProbeOut: {
            /** Session */
            session: boolean;
        };
        /**
         * SessionsOut
         * @description GET /auth/sessions response: the caller's live sessions.
         *
         *     ``current`` is the session id embedded in the caller's own access token
         *     (``sid`` claim, ADR-0002). ``null`` means the token carried no ``sid``
         *     claim, so the current session cannot be pinpointed (revoke-others will
         *     refuse with 409 in that case).
         */
        SessionsOut: {
            /** Current */
            current: string | null;
            /** Items */
            items: components["schemas"]["SessionItemOut"][];
        };
        /** SheetsExportRequest */
        SheetsExportRequest: {
            /** Month */
            month?: string | null;
            /** Sheet */
            sheet: string;
        };
        /** SheetsExportResult */
        SheetsExportResult: {
            /** Rows */
            rows: number;
        };
        /** SheetsStatus */
        SheetsStatus: {
            /** Configured */
            configured: boolean;
            /** Sa Email */
            sa_email: string | null;
        };
        /**
         * UserOut
         * @description Public view of a profile.
         */
        UserOut: {
            /** Email */
            email: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Issuperadmin
             * @default false
             */
            isSuperadmin: boolean;
            /**
             * Issuspended
             * @default false
             */
            isSuspended: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VoiceParseIn
         * @description POST /voice/parse body.
         */
        VoiceParseIn: {
            /** Text */
            text: string;
        };
        /** VoiceParseOut */
        VoiceParseOut: {
            /** Confidence */
            confidence: number;
            /** Items */
            items: components["schemas"]["ParsedItem"][];
        };
        /** YearlyReportOut */
        YearlyReportOut: {
            /** By Group */
            by_group: {
                [key: string]: string;
            };
            /** By Month */
            by_month: components["schemas"]["ReportByMonth"][];
            /** Count */
            count: number;
            /** Total */
            total: string;
            /** Year */
            year: number;
        };
        /**
         * AdminPlatformStatsOut
         * @description Global system-wide statistics for superadmins.
         */
        AdminPlatformStatsOut: {
            /** Activerecurring */
            activeRecurring: number;
            /** Totalamount */
            totalAmount: string;
            /** Totaldebts */
            totalDebts: number;
            /** Totalexpenses */
            totalExpenses: number;
            /** Totalusers */
            totalUsers: number;
        };
        /**
         * AdminUserItemOut
         * @description User row in the admin users list.
         */
        AdminUserItemOut: {
            /**
             * Budgetcount
             * @default 0
             */
            budgetCount: number;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Debtcount
             * @default 0
             */
            debtCount: number;
            /** Email */
            email: string | null;
            /**
             * Expensecount
             * @default 0
             */
            expenseCount: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Issuperadmin */
            isSuperadmin: boolean;
            /** Lang */
            lang: string;
            /** Name */
            name: string;
            /**
             * Recurringcount
             * @default 0
             */
            recurringCount: number;
            /** Theme */
            theme: string;
            /**
             * Totalexpense
             * @default 0.00
             */
            totalExpense: string;
            /**
             * Issuspended
             * @default false
             */
            isSuspended: boolean;
        };
        /**
         * AdminUserListOut
         * @description List of users with pagination total.
         */
        AdminUserListOut: {
            /** Items */
            items: components["schemas"]["AdminUserItemOut"][];
            /** Total */
            total: number;
        };
        /**
         * AdminUserBudgetOut
         * @description User budget configuration.
         */
        AdminUserBudgetOut: {
            /** Cats */
            cats: {
                [key: string]: string;
            };
            /** Total */
            total: string;
            /**
             * Updatedat
             * @default null
             */
            updatedAt: string | null;
        };
        /**
         * AdminUserDetailOut
         * @description Comprehensive user data summary for superadmins.
         */
        AdminUserDetailOut: {
            /** @default null */
            budget: components["schemas"]["AdminUserBudgetOut"] | null;
            /**
             * Currentmonthexpense
             * @default 0.00
             */
            currentMonthExpense: string;
            /**
             * Netdebt
             * @default 0.00
             */
            netDebt: string;
            /**
             * Totalborrow
             * @default 0.00
             */
            totalBorrow: string;
            /**
             * Totallend
             * @default 0.00
             */
            totalLend: string;
            user: components["schemas"]["AdminUserItemOut"];
        };
        /**
         * AdminUserExpensesOut
         * @description List of expenses for a specific user.
         */
        AdminUserExpensesOut: {
            /** Items */
            items: components["schemas"]["ExpenseOut"][];
            /** Total */
            total: number;
        };
        /**
         * AdminUserDebtsOut
         * @description List of debts for a specific user.
         */
        AdminUserDebtsOut: {
            /** Items */
            items: components["schemas"]["DebtOut"][];
            /** Total */
            total: number;
        };
        /**
         * AdminUserRecurringOut
         * @description List of recurring rules for a specific user.
         */
        AdminUserRecurringOut: {
            /** Items */
            items: components["schemas"]["RecurringOut"][];
            /** Total */
            total: number;
        };
        /**
         * AdminUserSuspendIn
         * @description Payload to suspend or unsuspend a user.
         */
        AdminUserSuspendIn: {
            /**
             * Suspended
             * @default true
             */
            suspended: boolean;
        };
        /**
         * AdminUserActionOut
         * @description Result of an admin action on a user.
         */
        AdminUserActionOut: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Message */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout_cookie_api_v1_auth_logout_cookie_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_cookie_api_v1_auth_refresh_cookie_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthOut"] | components["schemas"]["SessionProbeOut"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_v1_auth_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionsOut"];
                };
            };
        };
    };
    revoke_other_sessions_api_v1_auth_sessions_revoke_others_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokeOthersOut"];
                };
            };
        };
    };
    get_budgets_api_v1_budgets_get: {
        parameters: {
            query?: {
                ym?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_budgets_api_v1_budgets_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BudgetIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_debts_api_v1_debts_get: {
        parameters: {
            query?: {
                status?: "open" | "settled" | "all";
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebtListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_debt_api_v1_debts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DebtIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebtOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_debt_api_v1_debts__debt_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                debt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_debt_api_v1_debts__debt_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                debt_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DebtUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebtOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pay_debt_api_v1_debts__debt_id__pay_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                debt_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DebtPayIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebtPayOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_expenses_api_v1_expenses_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                q?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_expense_api_v1_expenses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_expenses_bulk_api_v1_expenses_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkExpensesIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkExpensesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_khata_categories_api_v1_expenses_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KhataListOut"];
                };
            };
        };
    };
    delete_expense_api_v1_expenses__expense_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expense_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_expense_api_v1_expenses__expense_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expense_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_backup_json_api_v1_export_backup_json_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupEnvelope"];
                };
            };
        };
    };
    export_expenses_csv_api_v1_export_expenses_csv_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_sheets_api_v1_export_sheets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SheetsExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SheetsExportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sheets_status_api_v1_export_sheets_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SheetsStatus"];
                };
            };
        };
    };
    healthz_api_v1_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Healthz"];
                };
            };
        };
    };
    import_restore_api_v1_import_restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestoreOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recurring_api_v1_recurring_get: {
        parameters: {
            query?: {
                active?: boolean | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_recurring_api_v1_recurring_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecurringIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_recurring_api_v1_recurring_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringRunOut"];
                };
            };
        };
    };
    delete_recurring_api_v1_recurring__recurring_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recurring_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_recurring_api_v1_recurring__recurring_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recurring_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecurringUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    monthly_report_api_v1_reports_monthly_get: {
        parameters: {
            query?: {
                ym?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    yearly_report_api_v1_reports_yearly_get: {
        parameters: {
            query?: {
                year?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YearlyReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_transcript_api_v1_voice_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoiceParseIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceParseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Healthz"];
                };
            };
        };
    };
    get_platform_stats_api_v1_admin_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPlatformStatsOut"];
                };
            };
        };
    };
    list_admin_users_api_v1_admin_users_get: {
        parameters: {
            query?: {
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserListOut"];
                };
            };
        };
    };
    get_admin_user_detail_api_v1_admin_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserDetailOut"];
                };
            };
        };
    };
    delete_admin_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserActionOut"];
                };
            };
            /** @description Bad Request (e.g. self-delete) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Superadmin access required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_admin_user_expenses_api_v1_admin_users__user_id__expenses_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserExpensesOut"];
                };
            };
        };
    };
    get_admin_user_debts_api_v1_admin_users__user_id__debts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserDebtsOut"];
                };
            };
        };
    };
    get_admin_user_recurring_api_v1_admin_users__user_id__recurring_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserRecurringOut"];
                };
            };
        };
    };
    suspend_admin_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUserSuspendIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserActionOut"];
                };
            };
            /** @description Bad Request (e.g. self-suspend) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Superadmin access required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
